name:                filtercsvxacts
version:             0.1.0.0
github:              "aparkerlue/filtercsvxacts"
license:             BSD-3-Clause
author:              "Alan Parker Lue"
maintainer:          "83985+aparkerlue@users.noreply.github.com"
copyright:           "Copyright: (c) 2024 Alan Parker Lue"

extra-source-files:
- README.org
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Financial

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.org file.
description:         Please see the README on GitHub at <https://github.com/aparkerlue/filtercsvxacts#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  filtercsvxacts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filtercsvxacts

tests:
  filtercsvxacts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filtercsvxacts
